### PR TITLE
Update esp.hpp

### PR DESCRIPTION
**Pull request by numero69**

### CODE REVIEW

**Comment by cristeigabriel** [comment]
TBH

1. Position seems unfit, try catching it within a wrapper like:
`inline void HealthText(...)`
2. instead of to_wstring use std::wstring_view{ player->Health() }

**Comment by cristeigabriel** [comment]
Also lowercase X & Y

**Comment by cristeigabriel** [comment]
inline void DrawHealth( int x, int y, Utils::Color ColorMain, std::wstring_view{ int Health; } ) noexcept {


this line is our issue


make it this:
  inline void DrawHealth( int x, int y, Utils::Color ColorMain, CS::Classes::CCSPlayer Player ) noexcept {

then in the code function

RenderText(blablabla, wstring_view{ Player->Health() }

then call stuff like this

DrawHealth( position, position, color, Player ) (in runesp)

**Comment by numero69** [comment]
How do you use wstring_view? I have hard time compiling it without errors and researching on google did not help.

**Comment by cristeigabriel** [comment]
I'm sorry, it was an issue on my end, wstring_view cannot convert integral types, this should be the code
`  inline void DrawHealth( int x, int y, Utils::Color ColorMain, CS::Classes::CCSPlayer * Player ) noexcept {
    Utils::Render::RenderText( x + 1, y + 1, Utils::Render::Verdana, ColorMain, std::to_wstring( Player->Health( ) ) );
  }`

**Comment by cristeigabriel** [comment]
https://en.cppreference.com/w/cpp/string/basic_string_view There's some documentation on string_view. W stands for Wide as in Wide Character to take unicode and such

**Pull request merged**
